### ISSUE TITLE
Markdown Tables not working in Outlook Desktop

### ISSUE THREAD

**Issue by HTEredrock** [MicrosoftDocs/power-automate-docs#318]
Using the following Markdown, 

`
| Request Details |  |
|---|---|
| Article Description | Cell |
| What do you want to do? | Cell |
| Article Number | Cell |
| GL Code for Purchase Orders | Cell |
| Vendor Code | Cell |
| Account Assignment Group | Cell |
| Article Pricing Group | Cell |
| Comments | Cell |
`

Results in the following in Outlook on the Web:

![image](https://user-images.githubusercontent.com/26794567/91440503-fe606c00-e86e-11ea-84ca-72be374da809.png)

And the following on Outlook desktop, version 16.0.13127.20266

![image](https://user-images.githubusercontent.com/26794567/91440712-4a131580-e86f-11ea-95c1-e82f63387b05.png)

Something is very clearly not working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e22eb42c-6ab3-854c-c229-569f1ca6d2ea
* Version Independent ID: b86cc920-b40d-3a2c-c88b-a36e3692fbbc
* Content: [Use markdown to format Power Automate approvals - Power Automate](https://docs.microsoft.com/en-us/power-automate/approvals-markdown-support)
* Content Source: [articles/approvals-markdown-support.md](https://github.com/MicrosoftDocs/power-automate-docs/blob/live/articles/approvals-markdown-support.md)
* Service: **flow**
* GitHub Login: @gcorvera
* Microsoft Alias: **gcorvera**

**Comment by MSFTMan** [comment]
@HTEredrock  Thanks for reporting this issue. We'll investigate this.

**Comment by Dean-Haas** [comment]
@dblyth-msft Can you please evaluate whether this is a docs issue? Let me know if there's anything needed to be updated in docs to help with this.

**Comment by dblyth-msft** [comment]
This is a known bug in Outlook when the requestor feature is used ("Requested by"). This should be fixed by the end of the month or so.
________________________________

**Comment by Dean-Haas** [comment]
Closing this out as a known issue. Thanks everyone.

**Comment by ITKJuhoon** [comment]
Hi, 
Any updates on this issue? I am still experiencing the same table issue on Outlook Desktop.
